# commands
# aws cloudformation create-stack --stack-name T1 --template-body file://HT2.yml  --parameters file://Para.json --region=us-east-1
# aws cloudformation update-stack --stack-name $1 --template-body file://$2  --parameters file://$3 --region=us-east-1
# aws cloudformation create-stack --stack-name $1 --template-body file://$2  --parameters file://$3 --capabilities "CAPABILITY_IAM" "CAPABILITY_NAMED_IAM" --region=us-east-1


AWSTemplateFormatVersion: 2010-09-09
Description: Hosam Kasbaa / Udacity  DevOps

Parameters:
    EnvironmentName:
        Type: String
        Description: Name of the environment

    VpcCIDR:
        Type: String
        Default: 10.0.0.0/16




Resources:
    VPC:
        Type: AWS::EC2::VPC
        Properties:
            CidrBlock: !Ref VpcCIDR
            EnableDnsHostnames: true
            Tags:
                - Key: Name
                  Value: !Ref EnvironmentName
    InternetGateway:
        Type: AWS::EC2::InternetGateway
        Properties:
            Tags:
                - Key: Name
                  Value: !Ref EnvironmentName

    InternetGatewayAttachment:
        Type: AWS::EC2::VPCGatewayAttachment
        Properties:
            InternetGatewayId: !Ref InternetGateway
            VpcId: !Ref VPC


